language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

before_install:
  - composer self-update
  - composer update
  - composer install --dev --prefer-source --no-interaction

script: vendor/bin/phpunit --configuration tests/phpunit.xml --coverage-text
